### ISSUE TITLE
indexing a slice with an array causes an error inside ndslice

### ISSUE THREAD

**Issue by John-Colvin** [9il/dip80-ndslice#14]
e.g. `mySlice[[1,2,3]]` gives

```
/Users/john/.dub/packages/mir-0.10.2/source/mir/ndslice/slice.d(1556): Error: no property 'i' for type 'int[]'
/Users/john/.dub/packages/mir-0.10.2/source/mir/ndslice/slice.d(1557): Error: no property 'j' for type 'int[]'
/Users/john/.dub/packages/mir-0.10.2/source/mir/ndslice/slice.d(1557): Error: no property 'i' for type 'int[]'
test.d(8): Error: template instance mir.ndslice.slice.Slice!(3LU, ulong*).Slice.opIndex!(int[]) error instantiating
```

it should either work or should error at the API level, not internally.

**Comment by 9il** [comment]
This code should compiles with `v0.11.1`.
