### PR TITLE
fix #14

### LINKED ISSUE #14: indexing a slice with an array causes an error inside ndslice
e.g. `mySlice[[1,2,3]]` gives

```
/Users/john/.dub/packages/mir-0.10.2/source/mir/ndslice/slice.d(1556): Error: no property 'i' for type 'int[]'
/Users/john/.dub/packages/mir-0.10.2/source/mir/ndslice/slice.d(1557): Error: no property 'j' for type 'int[]'
/Users/john/.dub/packages/mir-0.10.2/source/mir/ndslice/slice.d(1557): Error: no property 'i' for type 'int[]'
test.d(8): Error: template instance mir.ndslice.slice.Slice!(3LU, ulong*).Slice.opIndex!(int[]) error instantiating
```

it should either work or should error at the API level, not internally.

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by 9il** [comment]
@John-Colvin no error looks like:

```
source/mir/ndslice/slice.d(467,19): Error: template mir.ndslice.slice.Slice!(3LU, Result).Slice.opIndex cannot deduce function from argument types !()(int[]), candidates are:
source/mir/ndslice/slice.d(1498,14):        mir.ndslice.slice.Slice!(3LU, Result).Slice.opIndex(Indexes...)(Indexes _indexes) if (isFullPureIndex!Indexes)
source/mir/ndslice/slice.d(1539,10):        mir.ndslice.slice.Slice!(3LU, Result).Slice.opIndex(Slices...)(Slices slices) if (isPureSlice!Slices)
```

is it ok for you?

**Comment by 9il** [comment]
This code should compiles with `v0.11.1`.
